const ADD_POSITIONS = 'ADD_POSITIONS';

const ADD_FILTER = 'ADD_FILTER';
const DELETE_FILTER = 'DELETE_FILTER';
const RESET_FILTERS = 'RESET_FILTERS';

export { ADD_POSITIONS, ADD_FILTER, DELETE_FILTER, RESET_FILTERS };
